Network queue reconstruction
haiwen/seafile-iOS pull request #409
Opened 2024-12-18 02:03 UTC by henry9610

Initial Network queue reconstruction. SeafTaskQueue remove, change to NSOperationQueue.

2024-12-22 16:08 UTC, lilthree requested changes

2024-12-22 16:08 UTC, lilthree commented on Pod/Classes/SeafDataTaskManager.m
> +        switch (status) {
这里只是网络变化会生效，进入后台后任务失效的时候这里的回调不会走。另外如果是服务器有问题上传下载任务段时间内大量失败的情况也需要考虑。

2024-12-23 02:05 UTC, henry9610 commented on seafile/SeafAppDelegate.m
> +                    [accountQueue pauseAllTasks];
“之前续几次还能持续几百秒”我从来没续成功过，都是30s就结束，而且续失败会引发app重启导致之前浏览进度丢失问题。系统调用到这里是为了把没做完的工作结束收尾，不是开启另一个后台任务。如果你有能持续几百秒的成功案例，发出看一下，看看具体的机型版本和可触发概率，再研究一下是否可行。

2024-12-23 02:07 UTC, henry9610 commented on seafile/SeafAppDelegate.m
> +                    [accountQueue pauseAllTasks];
“根据定位改变上传的逻辑也失效了”这里是测过吗，我通过代码看没有什么问题

2024-12-23 02:33 UTC, henry9610 commented on Pod/Classes/SeafAccountTaskQueue.m
> +    [operation addObserver:self forKeyPath:@"isExecuting" options:NSKeyValueObservingOptionNew context:NULL];
目前在SeafAccountTaskQueue中监听和处理ongoingTasks、waitingTasks等数组的状态有什么问题？代码逻辑不流畅的点在哪里？

2024-12-23 02:54 UTC, henry9610 commented on Pod/Classes/SeafAccountTaskQueue.m
> +        NSNotification *note = [NSNotification notificationWithName:@"photosDidChange" object:nil userInfo:@{@"force" : @(YES)}];
这里是备份照片失败后的重试机制，    if (self.conn.photoBackup.photosArray.count > 0 && self.ongoingTasks.count == 0 && self.waitingTasks.count == 0) 这三个条件是有没备份完的照片且队列没有可执行的任务，这时候需要对没备份完的照片重新上传。
这个场景下有两种方式：只重新传photosArray中的和扫描一遍照片库。我认为扫描一遍照片库比较稳妥，因为这个判断条件轻易不会触发。
改成你代码中的条件，会很容易触发进入判断，再进行后续操作。如果经常备份失败，可以考虑进行修改

2024-12-23 03:08 UTC, henry9610 commented on Pod/Classes/SeafDataTaskManager.m
> +        switch (status) {
“进入后台后任务失效的时候这里的回调不会走”这里不是太理解，进入后台任务失效的时候任务已经停止了，队列中没有可执行任务，网络变化已经不考虑了。
大量失败的情况有重试机制，这里可以在交互上优化一下，添加失败原因的提示，比如空间已满之类的

2024-12-23 05:52 UTC, henry9610 commented on Pod/Classes/SeafUploadFile.m
> +            if ([dataUTI isEqualToString:@"public.heic"]) {
可以写在一起代码会更整洁。需要新建一个plist，添加对应新方法，原有的是jpg -> image/jpeg，需要重新写成 public.jpeg -> jpg

2024-12-23 06:24 UTC, henry9610 commented on Pod/Classes/SeafAccountTaskQueue.m
> +        @synchronized (taskArray) {
✅

2024-12-23 06:24 UTC, henry9610 commented on Pod/Classes/SeafFile.m
> +        dispatch_async(dispatch_get_main_queue(), ^{
✅

2024-12-23 10:30 UTC, henry9610 commented on Pod/Classes/SeafDataTaskManager.m
> +        switch (status) {
这里有个回到前台后网络变为可用时，备份任务重复添加的问题

2024-12-23 15:13 UTC, lilthree commented on seafile/SeafAppDelegate.m
> +                    [accountQueue pauseAllTasks];
看下是不是系统设置里面没有打开后台刷新，我测试过程中后台任务能续十来次30s的任务，这个测试结果我之前跟你说过。根据定位改变时后台状态处于非活跃状态，这里任务都也就都暂停。

2024-12-23 15:23 UTC, lilthree commented on Pod/Classes/SeafAccountTaskQueue.m
> +    [operation addObserver:self forKeyPath:@"isExecuting" options:NSKeyValueObservingOptionNew context:NULL];
1、SeafAccountTaskQueue监听不同operation的状态，状态回调的delegate中还需要判断不同类，代码过于耦合。
2、addTask 的代码在一处，delegate的代码在另一处，阅读起来就不流畅。改成添加的时候就通过回调的给出状态，代码阅读性上更好。

2024-12-23 15:31 UTC, lilthree commented on Pod/Classes/SeafDataTaskManager.m
> +        switch (status) {
主要是需要考虑避免出现短时间内任务大量失败，队列里面的任务段时间内经历添加-->开始-->失败-->添加的过程，然后导致app内存和cpu暴增的情况。

2024-12-24 10:28 UTC, henry9610 commented on seafile/SeafAppDelegate.m
> +                    [accountQueue pauseAllTasks];
我测了一下在iOS 17.6.1 ,iPhone 12 pm上连接xcode在debug模式下可以在后台收到ExpirationHandler调用后，继续传输可以持续很长时间。但是appstore上下载的不行，会30s左右停止。你那是用什么环境测的，具体的测试条件看一下，研究一下这里能否后台继续。

2024-12-26 01:35 UTC, henry9610 commented on Pod/Classes/SeafDataTaskManager.m
> +        switch (status) {
这里添加了空间已满或者收到连续5个相同错误代码暂停队列

2024-12-26 05:48 UTC, lilthree approved these changes

2024-12-26 07:12 UTC, henry9610 commented on Pod/Classes/SeafAccountTaskQueue.m
> +    [operation addObserver:self forKeyPath:@"isExecuting" options:NSKeyValueObservingOptionNew context:NULL];
1.你指的是在监听到的方法里需要判断SeafUploadOpeartion和SeafDownloadOperation吧？这里只有判断了这两个类型，我觉得应该算不上过于耦合。
状态监听放到Operation里在判断类型多的时候有优势，再一个就是代码看起来简洁一些，但是状态监听完全移到operation类中，它还需要处理自身状态，可能导致职责混乱，我认为当前逻辑有状态监听集中，便于管理的优势。目前版本专注于队列的优化，这里可以作为一个考虑的点下个版本做代码优化的时候可以考虑进去。
2.“添加的时候就通过回调的给出状态”是这样吧
- (void)addOperation:(SeafOperation *)operation {
    operation.stateChangeHandler = ^(NSString *state, NSError *error) {
        if ([state isEqualToString:@"started"]) {
            // 更新 ongoingTasks
        } else if ([state isEqualToString:@"finished"]) {
            // 任务完成逻辑
        } else if ([state isEqualToString:@"failed"]) {
            // 任务失败逻辑
        }
    };
    [self.taskQueue addOperation:operation];
}
如果block太多同样也不利于阅读，也可以作为下一步代码优化的时候考虑进去。

2024-12-26 07:16 UTC, henry9610 commented on Pod/Classes/SeafPhotoBackupTool.m
> +        @synchronized(self.photosArray) {
这里是赋值，用setter方法，可以新加一个，跟getter方法没有什么关系

2024-12-26 08:28 UTC, merged